### ISSUE TITLE
bacgrkound Color, Bar Color

### ISSUE THREAD

**Issue by alexookah** [tungvoduc/DTPagerController#11]
These two arguments would be nice as a configuration when creating the PagerController()

let pagerController = PagerController()
pageController.bgColor = UIColor.grey
pageController.scrollIndicatorColor = UIColor.red

**Comment by tungvoduc** [comment]
@Alexookah PagerController is a UIViewController so you can change its background color by setting its view's background color. Same with the bar color, pageSegmentedControl.backgroundColor to change its color. Except with scroll indicator color, there is no public API for that, but what I can do is to expose the pageScrollView.

**Comment by alexookah** [comment]
thank you very much for your answer.
exposing the pagescrollview would be nice.

one more question:
is there a option to disable bounces? so that you can use the back to previous swipe?

**Comment by tungvoduc** [comment]
@Alexookah Do you mean UIScrollView bounces? After pageScrollView is exposed then you can disable it by setting pageScrollView.bounces = false. 
I just did not get why it has anything to do with go back to previous swipe so I will just answer those as separate questions. If you want to keep track of the previous tab index, you can set delegate and  implement the following delegate method of DTPagerControllerDelegate object:

```swift
func pagerController(_ pagerController: DTPagerController, willChangeSelectedPageIndex index: Int, fromPageIndex oldIndex: Int) {
    previousTabIndex = oldIndex // Store previous tab index
}
```

**Comment by alexookah** [comment]
no i meant if you are in homePage viewController when you push to a viewcontroller that is PageController. 
there is no way to get back to the previous view controller (homePage). using the swipe gesture from left corner and not the back button from navigation controller

**Comment by tungvoduc** [comment]
@Alexookah This should not have anything to do with DTPagerController. It is just a normal view controller so you should be able to pop back after push. If not then there must be something wrong in your code, please try with other view controller.

**Comment by tungvoduc** [comment]
@Alexookah Okay now I get it now. You should be able to pop back using edge swipe gesture. However, if you still want to disable scrolling, you can use this after pageScrollView being exposed:

```swift
pageScrollView.isScrollEnabled = false
```

**Comment by alexookah** [comment]
but that would disable the functionality scrolling right? and you could switch viewCotnrollers only by using the button.

Couldn't just add a functionality to identify geture on the left edge to go back?

**Comment by tungvoduc** [comment]
@Alexookah Yes exactly! But the scrolling and edge pop gesture are working fine together for me. I will check again soon.

**Comment by tungvoduc** [comment]
@Alexookah Okay I already checked, everything is working fine. If you want to check, you can add into sample project a button and make it push to another PagerController, you should still be able to go back with pop gesture.

**Comment by tungvoduc** [comment]
@Alexookah Version 1.1.2 is out. pageScrollView is now accessible. Enjoy!
