### ISSUE TITLE
Orientation Rotating issues

### ISSUE THREAD

**Issue by alexookah** [tungvoduc/DTPagerController#15]
When rotating the device in landscape for examble. there seems some issues in auto laytout.

check this video:
https://streamable.com/f4h5o

can this be resolved?

**Comment by tungvoduc** [comment]
@Alexookah I will fix it and let you know when it's done! Thanks anyway.

**Comment by tungvoduc** [comment]
@Alexookah It should be fixed now. Please check version **1.1.5**.

**Comment by alexookah** [comment]
yes it seems its ok. the layout issues now.
thanks
