### ISSUE TITLE
'UIScrollView' is not convertible to 'DTPagerController'

### ISSUE THREAD

**Issue by alexookah** [tungvoduc/DTPagerController#18]
trying to run in my project

and i get this issue. i would guess its something swift 3.2 with swift 4 running the library?

**Comment by tungvoduc** [comment]
@Alexookah DTPagerController is written in Swift 4. Can you show me where the error is shown.

**Comment by alexookah** [comment]
![screen shot 2017-10-18 at 21 04 27](https://user-images.githubusercontent.com/9624843/31734632-f9cdd726-b447-11e7-9099-fbec0907549a.png)

**Comment by alexookah** [comment]
i am still using swift 3.2 and i guess some other people. (until all libraries are swift 4 available.)

**Comment by alexookah** [comment]
or could i update to swift 4 and use libraries swift 3 as well ? is swift 4 available for ios 9?

**Comment by tungvoduc** [comment]
@Alexookah This issue should not be related to Swift 4. This is weird. Can you try to make it work somehow?

**Comment by alexookah** [comment]
i see that you moved the observer to viewDidLoad() in version 1.1.6. now everything works great.
Good Job.
closing this issue
