### ISSUE TITLE
Question: How to add in PagerViewController a header UIView

### ISSUE THREAD

**Issue by alexookah** [tungvoduc/DTPagerController#21]
is it possible to add a header view above the controller ? like in the image below?

![31812003-421037c0-b58a-11e7-8ede-92e67250f767](https://user-images.githubusercontent.com/9624843/31852785-d3d5c06a-b686-11e7-99c1-8a6cba19336d.png)

can i use the pagerviewcontroller somehow in the storyboard to have some customization to add extra things?

**Comment by tungvoduc** [comment]
@Alexookah Yes! override **viewDidLayoutSubviews**, remember to call **super.viewDidLayoutSubviews()** before implementing your own customization.
