### ISSUE TITLE
Can the segment control display insfinite tab bar items?

### ISSUE THREAD

**Issue by KaushikShivam** [tungvoduc/DTPagerController#23]
Hello. Thank you for the wonderful library. I have to implement around 8 tabs. Is that possible to make the segment control scrollable?

**Comment by tungvoduc** [comment]
@KaushikShivam Yes! I am currently working on it. I will try to release it asap.

**Comment by KaushikShivam** [comment]
Any updates? :)

**Comment by iamabhiee** [comment]
Any updates?

**Comment by Narek1994** [comment]
any news?

**Comment by tungvoduc** [comment]
@KaushikShivam @iamabhiee @Narek1994 Sorry that I was so busy at my workplace and then hit heavily by a sickness and I got just recover from it. I am back on working with this new feature now and will try to publish it soon.

**Comment by tungvoduc** [comment]
@KaushikShivam @iamabhiee @Narek1994 New version **2.0.0** is expected to be released anytime soon. This one will support custom SegmentedControl, you can bring your own SegmentedControl or any 3rd party SegmentedControl to DTPagerController.

**Comment by tungvoduc** [comment]
@KaushikShivam @iamabhiee @Narek1994 I just published version 2.0.0 which supports custom segmented control. You can use your own custom segmented control from now on to support your desired UI. Please take a look at README and check sample project for more detail.
