### ISSUE TITLE
Weird navigation controller's behaviour 

### ISSUE THREAD

**Issue by CarioniStefano** [tungvoduc/DTPagerController#37]
Hello,

I'm getting a weird bug in my application, and I'm getting the same problem in the Example provided in this library.

Step to reproduce:
1 open the example app
2 fast switch between page "One" viewcontroller and "Two" viewcontroller for 4 or 5 time
3 tap on the "push" button

As you can see the push doesn't perform because the navigation controller is nil.

**Comment by tungvoduc** [comment]
@CarioniStefano Thank you for reporting! I will take a look at it. I might already know what causes it.

**Comment by tungvoduc** [comment]
@CarioniStefano version `2.0.3` should fix this issue :)

**Comment by CarioniStefano** [comment]
@tungvoduc When will it be available?
