### ISSUE TITLE
Change selectedPageIndex on first time without animation

### ISSUE THREAD

**Issue by ArturBaghdas** [tungvoduc/DTPagerController#38]
Is it possible to add functionality to change initialPageIndex without animation ?

**Comment by tungvoduc** [comment]
@ArturBaghdas This is a good idea. I will update it asap.

**Comment by tungvoduc** [comment]
@ArturBaghdas version `2.0.4` is out. You can use as following:

```swift
pagerController.setSelectedPageIndex(1, animated: false)
```

**Comment by ArturBaghdas** [comment]
Thanks!!!
