### ISSUE TITLE
Parallax header

### ISSUE THREAD

**Issue by mrhaxic** [tungvoduc/DTPagerController#4]
Hello,

Is it possible to add a header view to be considered as parallax header ?

Thanks

**Comment by tungvoduc** [comment]
@mrhaxic This is not related to the project itself. I actually had to do the same thing that you mention. I had to create another container view controller to make parallax effect with header in our product. This will require some amount of code. You can check this project: https://github.com/tungvoduc/DTParallaxViewController to have some idea how to do it.

**Comment by mrhaxic** [comment]
@tungvoduc  Thanks a lot, I will check the soonet.
