### ISSUE TITLE
PagerController disappear after pushViewController

### ISSUE THREAD

**Issue by CarioniStefano** [tungvoduc/DTPagerController#41]
Hello,

I'm experiencing when I try to push a viewController from the DTPagerController.

The push works, but when I get back from the "detail" view the controller doesn't show the pages.
They are still there because if I swipe it work, but it's impossible to see the name of the page.

See attached screenshot.

Thanks,

Carioni Stefano
BEFORE
![Simulator Screen Shot - iPhone X - 2019-03-19 at 16 14 44](https://user-images.githubusercontent.com/12976725/54617878-5ed86080-4a62-11e9-9978-de3769462aab.png)
AFTER
![Simulator Screen Shot - iPhone X - 2019-03-19 at 16 14 50](https://user-images.githubusercontent.com/12976725/54617875-5e3fca00-4a62-11e9-857a-eaa152ad0a9b.png)

**Comment by tungvoduc** [comment]
@CarioniStefano Could you somehow make a simplified version of this view controller and send it to me? Or maybe describe the hierarchy of the tabbar's child view controller.
