### ISSUE TITLE
Disable/ Enable segments click

### ISSUE THREAD

**Issue by hemaks777** [tungvoduc/DTPagerController#42]
Hi ,
 I want to disable the other segments click on first screen and enable it only after the button click on first screen. Could you please tell me how can I do this?

**Comment by tungvoduc** [comment]
@hemaks777 You can disable segmented control interaction and disable scroll view scrollEnabled.
```swift
pageSegmentedControl.isEnabled = false
pageScrollView.isScrollEnabled = false
```

**Comment by hemaks777** [comment]
Hi,

How to disable the click action of segmented control? I have removed the target of segmented control,  but still the click is working. Could you please tell me how to disable/enable particular segments based on certain criteria?

**Comment by tungvoduc** [comment]
@hemaks777 If you use default segmented control, you can do the following:
```swift
(pageController. pageSegmentedControl as! UISegmentedControl).setEnabled(: false, forSegmentAt: 0)
```
