### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by a-hasan** [tungvoduc/DTPagerController#43]
Hi,
i got weird behavior when using .forceRightToLeft for Arabic language.
could u pls add RTL support,,
Thanks,

**Comment by tungvoduc** [comment]
@a-hasan can you be a little bit clearer which part should support RTL? I'll take a look into that asap.

**Comment by a-hasan** [comment]
when force device to RTL layout by adding these two lines :

UIView.appearance().semanticContentAttribute = .forceRightToLeft
UINavigationBar.appearance().semanticContentAttribute = .forceRightToLeft
to didFinishLaunchingWithOptions ,,
App was become as the attached image 
![image](https://user-images.githubusercontent.com/6158528/64684192-b4cc1500-d495-11e9-8235-fa55eb9c43f9.png)
when you select tab then invalid controller will be presented

**Comment by tungvoduc** [comment]
@a-hasan Thank you! I will let you know when this issue is fixed!

**Comment by tungvoduc** [comment]
@a-hasan I already released new version which fixes RTL layout. Please check it. Leave me a star to support my work :)

**Comment by a-hasan** [comment]
@tungvoduc Thank you! it's working fine now.
you are the best :)

**Comment by a-hasan** [comment]
@tungvoduc thank you for your update,
scrolling is working fine now with the RTL layout, but there is an issue with the selected index at the initial stage (selected view is correct but scrollIndicator position is wrong) check the attached image pls.
 
![image](https://user-images.githubusercontent.com/6158528/64939220-63df6680-d871-11e9-9186-79b0bf14a817.png)

**Comment by tungvoduc** [comment]
@a-hasan I'll fix it!

**Comment by tungvoduc** [comment]
@a-hasan Version `3.1.1` should fix everything.

**Comment by a-hasan** [comment]
@tungvoduc Yes, everything is working fine now, Thanks!
