### ISSUE TITLE
iOS 13 problem corner radius

### ISSUE THREAD

**Issue by sourov2008** [tungvoduc/DTPagerController#46]
Default rounded corners which are introduced in iOS 13
Here is the problem. Please fix this

![image](https://user-images.githubusercontent.com/4990835/71612636-de878400-2bcb-11ea-80ad-c15ed6d36daf.png)

**Comment by tungvoduc** [comment]
@sourov2008 Thank you for reporting. I'll fix it asap and let you know.

**Comment by sourov2008** [comment]
Many thanks for your response. Please fix it ASAP. I am waiting for your
next release.



*Sincerely, *

*Shourob DattaEmail : sourovsuet@gmail.com <sourovsuet@gmail.com> | Mobile
: +8801719351186    *

**Comment by tungvoduc** [comment]
I think this is already fixed in latest version (does not happen in sample project). Please update your pod.

**Comment by sourov2008** [comment]
I am Using Version - 3.1.2

Problem is till existing


Please see the screenshots


*Sincerely, *

*Shourob DattaEmail : sourovsuet@gmail.com <sourovsuet@gmail.com> | Mobile
: +8801719351186    *

**Comment by sourov2008** [comment]
*I solved this problem by,*

        view.backgroundColor = Segment Bacground color





* I think this should be changed also in the Library.*



*Sincerely, *

*Shourob DattaEmail : sourovsuet@gmail.com <sourovsuet@gmail.com> | Mobile
: +8801719351186    *

**Comment by tungvoduc** [comment]
@sourov2008 I'll check how I can deal with this issue.

**Comment by sourov2008** [comment]
Thank you



*Sincerely, *

*Shourob DattaEmail : sourovsuet@gmail.com <sourovsuet@gmail.com> | Mobile
: +8801719351186    *

**Comment by sourov2008** [comment]
Did you find any solutions?

**Comment by pauljarysta** [comment]
@sourov2008 you can override func layoutSubviews() and apply layer.cornerRadius = 0

```
extension DTSegmentedControl {
    open override func layoutSubviews() {
        super.layoutSubviews()
        layer.cornerRadius = 0
        layer.masksToBounds = true
    }
}
```

**Comment by sourov2008** [comment]
Thanks You
