### ISSUE TITLE
DTPagerControllerDelegate methods not firing in 2.0.4

### ISSUE THREAD

**Issue by juliussss** [tungvoduc/DTPagerController#49]
Pod version: `~> 2.0.4` (Swift 4.2)

Tried console logging calls and debugging into all 3 methods:

```
didChangeSelectedPageIndex
willChangeSelectedPageIndex
pageScrollViewDidScroll
```

But none seem to be firing.

Any ideas?

**Comment by israa-jamal** [comment]
It happens with me too
