### ISSUE TITLE
Cannot find type 'UIViewController' in scope

### ISSUE THREAD

**Issue by multitudes** [tungvoduc/DTPagerController#54]
I removed the old version from the pod and installed DTPagerController with SPM.
The code is the same strangely , but after installing it with Swift Package Manager it does not compile.

And of course it says it cannot find it in scope, maybe because UIViewController is UIKit after all ? ;)

Here is the code giving problems:
```swift
import Foundation

public extension UIViewController {
    var pagerController: DTPagerController? {
        get {
            var viewController = parent

            while viewController != nil {
                if let containerViewController = viewController as? DTPagerController {
                    return containerViewController
                }
                viewController = viewController?.parent
            }

            return nil
        }
    }
}

```

and the screenshot. 

Too bad I would really like to use SPM but it will have to wait I guess? 

![Screenshot 2021-03-25 at 17 00 42](https://user-images.githubusercontent.com/29355828/112504451-127c3580-8d8c-11eb-8594-437d3b76dd7b.png)

**Comment by Ded77** [comment]
Hello, same problem for me :( 
The `UIKit` import seems missing.

**Comment by Ded77** [comment]
Strange, It should be fixed by https://github.com/tungvoduc/DTPagerController/commit/522ce1089d13ff862c352f0d5ba2d1ae5a7b63a0

**Comment by Ded77** [comment]
Ok, the last version of the library does not include this fix.
We have to pick the master branch to SPM @multitudes.

**Comment by Ded77** [comment]
Hello @tungvoduc, thanks for your library ! Is it possible to tag a new version with the SPM fix ?
Thank you

**Comment by tungvoduc** [comment]
@Ded77 Sorry for late reply. I'll get it done today.

**Comment by tungvoduc** [comment]
@multitudes @Ded77 Should be fixed now guys!

**Comment by multitudes** [comment]
Thank you!

**Comment by Ded77** [comment]
Great, thank you!

**Comment by Rutvik2699** [comment]
import UIKit 
would fix it!
