### ISSUE TITLE
Pod problems 

### ISSUE THREAD

**Issue by CavalcanteLeo** [tungvoduc/DTPagerController#8]
[!] Unable to find a specification for `DTPagerController`

**Comment by tungvoduc** [comment]
@CavalcanteLeo I don’t know yet what is wrong. I will investigate that and get back to you asap.

**Comment by alexookah** [comment]
i had the same problem checked in the library and fixd the issue.

check my pull request. @tungvoduc

**Comment by ghost** [comment]
try installing cocapods using brew and make sure it is linked properly, then try again. 
I found same issue and solved it that way.
