### ISSUE TITLE
How I can place image?

### ISSUE THREAD

**Issue by janapps** [tungvoduc/DTPagerController#9]
I need place image and text for each page title, how can do this?

**Comment by tungvoduc** [comment]
@zhanswift Not possible at the moment but it would be nice to have it. I will make it possible in new upcoming version.

**Comment by tungvoduc** [comment]
@zhanswift I just published version 2.0.0 which supports custom segmented control. You can use your own custom segmented control from now on to support your desired UI. Please take a look at README for more detail.
